name: gh-pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Publish with dotnet
      run: dotnet publish --configuration Release --output build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/wwwroot # The folder the action should deploy.
          CLEAN: true
